### ISSUE TITLE
找不到依赖包No module named 'peewee'

### ISSUE THREAD

**Issue by HanYaaaaaaa** [Dreamail/maimai-updater#3]
![_KNW667MJO`76Z(PL`E0DRQ](https://github.com/Dreamail/maimai-updater/assets/145742863/794062e8-e5b1-421b-8aa9-a2cbd356dc81)
peewee是已经安装了的，但是检测不到
![@P$GEZ$13SM_`9E$%8MV)64](https://github.com/Dreamail/maimai-updater/assets/145742863/cbda512d-9651-4862-991b-cbbe535efc51)

**Comment by Dreamail** [comment]
是通过nb-cli运行的吗
请检查venv内有没有安装依赖

（BTW 这个项目用了部分golang，可能需要安装gosdk进行本机编译 refer: https://github.com/go-python/gopy

**Comment by HanYaaaaaaa** [comment]
![ZAA32`P23(A520)8C%7HVOI](https://github.com/Dreamail/maimai-updater/assets/145742863/19693294-9a67-4677-99e6-9f46c123a097)
venv内已经安装了依赖
![image](https://github.com/Dreamail/maimai-updater/assets/145742863/839c6b24-c3ed-4d94-80b2-7dcaf54d9799)
我通过toml文件引入了本地插件，不知道这样引入插件是否正确

**Comment by HanYaaaaaaa** [comment]
> 是通过nb-cli运行的吗 请检查venv内有没有安装依赖
> 
> （BTW 这个项目用了部分golang，可能需要安装gosdk进行本机编译 refer: https://github.com/go-python/gopy

venv内已经安装了依赖
![~H8HA@0F~)__TWG`5SMO07O](https://github.com/Dreamail/maimai-updater/assets/145742863/a0dec2f8-66cb-42f2-ad9d-cb1b08c539d2)
我通过toml文件引入本地插件，不知道这样引入是否正确
![TV~_EI1)@8X~9EC)KI%{XQ9](https://github.com/Dreamail/maimai-updater/assets/145742863/21e4c26a-3110-4aee-9cf8-56976fec6d91)

**Comment by Dreamail** [comment]
手动激活venv并通过命令行运行Python终端
```
import peewee
```
看看能否导入包

（什么你是早五人（？

**Comment by HanYaaaaaaa** [comment]
> 手动激活venv并通过命令行运行Python终端
> 
> ```
> import peewee
> ```
> 
> 看看能否导入包
> 
> （什么你是早五人（？

![(N{`_MQS{A(L0FGX0 GP2BE](https://github.com/Dreamail/maimai-updater/assets/145742863/6dc89b07-f3e1-4921-9d6e-4e70d93f9d9c)
不行，还是报错了
其实是研究了一晚上，实在摸不着头脑才来提的issues（

**Comment by Dreamail** [comment]
> > 手动激活venv并通过命令行运行Python终端
> > 
> > ```
> > import peewee
> > ```
> > 
> > 看看能否导入包
> > 
> > （什么你是早五人（？
> 
> ![(N{`_MQS{A(L0FGX0 GP2BE](https://github.com/Dreamail/maimai-updater/assets/145742863/6dc89b07-f3e1-4921-9d6e-4e70d93f9d9c)
> 不行，还是报错了
> 其实是研究了一晚上，实在摸不着头脑才来提的issues（

那这就是说明了venv内没有安装这个包
请确认venv是否正确（nb-cli默认在.venv下创建（Windows应该是也吧

**Comment by HanYaaaaaaa** [comment]
> > > 手动激活venv并通过命令行运行Python终端
> > > ```
> > > import peewee
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 看看能否导入包
> > > （什么你是早五人（？
> > 
> > 
> > ![(N{`_MQS{A(L0FGX0 GP2BE](https://private-user-images.githubusercontent.com/145742863/296518112-6dc89b07-f3e1-4921-9d6e-4e70d93f9d9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjYzODEsIm5iZiI6MTcwNTIyNjA4MSwicGF0aCI6Ii8xNDU3NDI4NjMvMjk2NTE4MTEyLTZkYzg5YjA3LWYzZTEtNDkyMS05ZDZlLTRlNzBkOTNmOWQ5Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwOTU0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjNhYmE2NjUwOTVlZTZlM2MzNjgzMWRiOGI0Zjg2NjE3ZThlZjJiZWFmMzg1YWIyNGJmN2Y3ZDY0N2NmOTFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fDwxMtX_r9D4UQjPQm9IBbyZpypTMbGqJdj8uvo9pk8)
> > 不行，还是报错了
> > 其实是研究了一晚上，实在摸不着头脑才来提的issues（
> 
> 那这就是说明了venv内没有安装这个包 请确认venv是否正确（nb-cli默认在.venv下创建（Windows应该是也吧

研究了一天，解决了很多报错，我去venv内的site-packages看了一下，发现是只有依赖的info文件夹，没有py文件，最后从python文件夹那把py文件拷贝过去才解决的报错，然后现在还在解决这个报错
![C{4KQ)}JT8%LGM{KK%)4 ZP](https://github.com/Dreamail/maimai-updater/assets/145742863/5125103c-bd37-4f47-a059-2403fe311054)

**Comment by Dreamail** [comment]
这个是因为用了部分go实现
https://github.com/go-python/gopy
参考gopy文档安装环境
源码目录下有编译脚本

**Comment by HanYaaaaaaa** [comment]
> 这个是因为用了部分go实现 https://github.com/go-python/gopy 参考gopy文档安装环境 源码目录下有编译脚本

我安装了gopy并尝试去运行了编译脚本，出现了这个报错
![JE{AK((THEE@U 54Y_ XYKW](https://github.com/Dreamail/maimai-updater/assets/145742863/82b5a509-2d88-4d37-845e-ea8c26fc4e2d)

**Comment by HanYaaaaaaa** [comment]
> 这个是因为用了部分go实现 https://github.com/go-python/gopy 参考gopy文档安装环境 源码目录下有编译脚本

我通过gopy把go转换成了py，但是途中报错
![V3HVDU~{249V(DBFA K7A@7](https://github.com/Dreamail/maimai-updater/assets/145742863/1acd7822-4abe-4a33-bfd4-f270d9de45bb)
然后nb run之后报错这个
![4894PA9SNLXMGRLCGZ$BR2P](https://github.com/Dreamail/maimai-updater/assets/145742863/506d7b90-4e43-4c87-a64d-4689752171a5)

**Comment by Dreamail** [comment]
> > 这个是因为用了部分go实现 https://github.com/go-python/gopy 参考gopy文档安装环境 源码目录下有编译脚本
> 
> 我通过gopy把go转换成了py，但是途中报错
> ![V3HVDU~{249V(DBFA K7A@7](https://github.com/Dreamail/maimai-updater/assets/145742863/1acd7822-4abe-4a33-bfd4-f270d9de45bb)
> 然后nb run之后报错这个
> ![4894PA9SNLXMGRLCGZ$BR2P](https://github.com/Dreamail/maimai-updater/assets/145742863/506d7b90-4e43-4c87-a64d-4689752171a5)
> 

你环境下Python可执行文件是python3还是python，venv激活了吗
因为我没有Windows环境gopy的问题建议去gopy仓库看看

**Comment by HanYaaaaaaa** [comment]
> > > 这个是因为用了部分go实现 https://github.com/go-python/gopy 参考gopy文档安装环境 源码目录下有编译脚本
> > 
> > 
> > 我通过gopy把go转换成了py，但是途中报错
> > ![V3HVDU~{249V(DBFA K7A@7](https://private-user-images.githubusercontent.com/145742863/296615571-1acd7822-4abe-4a33-bfd4-f270d9de45bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzEwNjYsIm5iZiI6MTcwNTM3MDc2NiwicGF0aCI6Ii8xNDU3NDI4NjMvMjk2NjE1NTcxLTFhY2Q3ODIyLTRhYmUtNGEzMy1iZmQ0LWYyNzBkOWRlNDViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMjA2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjg0YWQzYjNmYzQ5NjdiMTI3ZGZhNjE4MTA5YTA5ODRlMzIyMjMzZDEzNTYxNzMyOTBkYjQ4YzQwMGI4ZGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ORqLkn-J4BLkRecwcZO0JkJZikuUjoTMd_5AsR7lb1Q)
> > 然后nb run之后报错这个
> > ![4894PA9SNLXMGRLCGZ$BR2P](https://private-user-images.githubusercontent.com/145742863/296615584-506d7b90-4e43-4c87-a64d-4689752171a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzEwNjYsIm5iZiI6MTcwNTM3MDc2NiwicGF0aCI6Ii8xNDU3NDI4NjMvMjk2NjE1NTg0LTUwNmQ3YjkwLTRlNDMtNGM4Ny1hNjRkLTQ2ODk3NTIxNzFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMjA2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTM3NTFiYWMwYzJhYzUyMTU0NzgyODRhNDU4OThhZDJkNmFkZWJiZWI0YjBhOTliN2M4OTE1NWE1NTliODQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7-AgDKIAdoPZwp85v9SqDX8YcUflNDiB9okczQ0H02w)
> 
> 你环境下Python可执行文件是python3还是python，venv激活了吗 因为我没有Windows环境gopy的问题建议去gopy仓库看看

gopy的问题解决了，bot能成功触发指令，但是在二维码登录那一块报错为无法重定向uri
![2b8c63e15b66443a13091559613b1d2](https://github.com/Dreamail/maimai-updater/assets/145742863/50d1f53a-4939-4916-95a5-fbed4b38c6fd)

**Comment by HanYaaaaaaa** [comment]
> > > 这个是因为用了部分go实现 https://github.com/go-python/gopy 参考gopy文档安装环境 源码目录下有编译脚本
> > 
> > 
> > 我通过gopy把go转换成了py，但是途中报错
> > ![V3HVDU~{249V(DBFA K7A@7](https://private-user-images.githubusercontent.com/145742863/296615571-1acd7822-4abe-4a33-bfd4-f270d9de45bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzYwNDksIm5iZiI6MTcwNTM3NTc0OSwicGF0aCI6Ii8xNDU3NDI4NjMvMjk2NjE1NTcxLTFhY2Q3ODIyLTRhYmUtNGEzMy1iZmQ0LWYyNzBkOWRlNDViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMzI5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWE0NDVjMTQwMDhlYTc5NWJjMTU2NzdjZTczMDg2OWJmNjhlOTU4YTA0MThkZDk3NzhkOTg0YzY1NDcxZjc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NDJVvqlkqZrOvWEhORbMwDxxnV0Fn-tHjSd1jCorO5c)
> > 然后nb run之后报错这个
> > ![4894PA9SNLXMGRLCGZ$BR2P](https://private-user-images.githubusercontent.com/145742863/296615584-506d7b90-4e43-4c87-a64d-4689752171a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzYwNDksIm5iZiI6MTcwNTM3NTc0OSwicGF0aCI6Ii8xNDU3NDI4NjMvMjk2NjE1NTg0LTUwNmQ3YjkwLTRlNDMtNGM4Ny1hNjRkLTQ2ODk3NTIxNzFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMzI5MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2U2MzJhODk0ODAyYzg1OGFmZTA0OWM2YjczY2ZiMTA5MWNjZTc4NTcwZmViNGNlN2E4YmJkNTZlMDQ0MWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DHnO05SgWEC-mz_3hK0spMt2nHOsly43GVJaKTSDPR0)
> 
> 你环境下Python可执行文件是python3还是python，venv激活了吗 因为我没有Windows环境gopy的问题建议去gopy仓库看看

我尝试去修改wechat.py
if result[1]:
                if result[1] == "200":
                    result = re.search(r'window.redirect_uri="(.*?)"', resp.text)
                    if result is None:
                        raise Exception("cant fetch redirect uri")
                    redirect_uri = result[1]
                    break
                if result[1] == "400":
                    raise Exception("login time out")
修正了比较逻辑，成功解决了重定向的报错，感谢

**Comment by Dreamail** [comment]
那我close了
有问题的话pr is welcomed
